# Generated by Django 6.0 on 2026-01-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_alter_choice_id_alter_material_id_alter_note_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="image",
            field=models.ImageField(blank=True, upload_to="subjects/"),
        ),
    ]
